/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penghitung_pajak;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ADITYA CP
 */
public class GUI_Pajak extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Pajak
     */
    public GUI_Pajak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kolomJenis = new javax.swing.JComboBox<>();
        kolomHarga = new javax.swing.JTextField();
        cekBaru = new javax.swing.JCheckBox();
        kolomHasil = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        kolomJumlah = new javax.swing.JComboBox<>();
        btnExit = new javax.swing.JButton();
        btnInfo1 = new javax.swing.JRadioButton();
        btnInfo2 = new javax.swing.JRadioButton();
        cekStnk = new javax.swing.JCheckBox();
        btnInfo3 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        kolomInfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kolomJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motor", "Mobil" }));
        kolomJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomJenisActionPerformed(evt);
            }
        });
        getContentPane().add(kolomJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 150, 30));

        kolomHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomHargaActionPerformed(evt);
            }
        });
        kolomHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kolomHargaKeyTyped(evt);
            }
        });
        getContentPane().add(kolomHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 290, 30));

        cekBaru.setText("Kendaraan Baru");
        cekBaru.setToolTipText("");
        cekBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBaruActionPerformed(evt);
            }
        });
        cekBaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cekBaruKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cekBaruKeyReleased(evt);
            }
        });
        getContentPane().add(cekBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 120, 30));

        kolomHasil.setEditable(false);
        getContentPane().add(kolomHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 300, 30));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, -1, 30));

        btnInfo.setText("Info");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, 20));

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, -1, 30));

        kolomJumlah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(kolomJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 290, 30));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitung_pajak/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        btnInfo1.setText("Besar Pajak");
        btnInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfo1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        btnInfo2.setText("SWDKLLJ");
        btnInfo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfo2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        cekStnk.setText("Perbarui STNK");
        cekStnk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekStnkActionPerformed(evt);
            }
        });
        cekStnk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cekStnkKeyPressed(evt);
            }
        });
        getContentPane().add(cekStnk, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 120, -1));

        btnInfo3.setText("BBNKB");
        btnInfo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfo3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, -1, -1));

        kolomInfo.setEditable(false);
        kolomInfo.setColumns(20);
        kolomInfo.setRows(5);
        jScrollPane2.setViewportView(kolomInfo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 320, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penghitung_pajak/Background UI.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
            //Menentukan Info biaya pajak
            if(btnInfo1.isSelected()){
            infopajak info1 = new infopajak();
            
            info1.setInfo("Data yang diperlukan untuk menentukan pajak : "
                + "\n1. Jenis kendaraan" + "\n2. Tipe Kendaraan"
                + "\n3. Tahun pembuatan" + "\n4. Cylinder(Besar CC)"
                + "\n5. Kegunaan Kendaraan (kendaraan pribadi/umum)");
            
            kolomInfo.setText(""+info1.getInfo());
            }        
            
            //Menentukan Info SWDKLLJ
            else if(btnInfo2.isSelected()){
            infopajak info2 = new infopajak();
            
            info2.setInfo("Sumbangan wajib dana kecelakaan lalu lintas "
                            + "\njalan (SWDKLLJ)."
                            + "\nSumbangan ini dikelola oleh jasa raharja."
                            + "\nUntuk motor besarannya Rp35 ribu,sedangkan "
                            + "\nmobil Rp143 ribu.");
            
            kolomInfo.setText(""+info2.getInfo());
            }
            
            //Menentukan Info Bea Balik Nama Kendaraan bermotor
            else if(btnInfo3.isSelected()){
            infopajak info3 = new infopajak();
            
            info3.setInfo("BBNKB adalah pajak atas penyerahan hak milik \n" +
                            "kendaraan bermotor sebagai akibat perjanjian\n" +
                            "dua pihak atau perbuatan sepihak atau keadaan\n" +
                            "yang terjadi karena jual beli, tukar menukar, hibah,\n" +
                            "warisan atau pemasukan ke dalam badan usaha.");
            
            kolomInfo.setText(""+info3.getInfo());
            }      
            
            else{
            kolomInfo.setText("");
            }   
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        kolomJenis.setSelectedIndex(0);
        kolomJumlah.setSelectedIndex(0);
        kolomHarga.setText("");
        kolomHasil.setText("");
        kolomInfo.setText("");
        cekBaru.setSelected(false);
        cekStnk.setSelected(false);        
        btnInfo1.setSelected(false); 
        btnInfo2.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int jawab = JOptionPane.showOptionDialog(this,
                "Apakah Anda Ingin Keluar?",
                "Keluar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "               Terima Kasih"
                    + "\nTelah Menggunakan Aplikasi Ini");
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void cekBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekBaruActionPerformed
        if(cekBaru.isSelected()){
            cekStnk.setSelected(false);
        }
    }//GEN-LAST:event_cekBaruActionPerformed

    private void kolomJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomJenisActionPerformed

    }//GEN-LAST:event_kolomJenisActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        int jenis = kolomJenis.getSelectedIndex();
        Integer harga = Integer.parseInt( kolomHarga.getText());
        int jumlah = kolomJumlah.getSelectedIndex();
        double pajak = 0;
        double hasil;
        int swdkllj = 0;
        int adm = 0;
        int bbnkb = 0;

        //Menentukan Sumbangan wajib dana kecelakaan lalu lintas jalan 
        switch(jenis){
            case (0):
                swdkllj = 35000;
                
        //Menentukan Biaya Administrasi Tanda Nomor Kendaraan & Bea Balik Nama Kendaraan bermotor
            if(cekBaru.isSelected()){
                bbnkb = harga * 10 / 100;
                adm = 60000;
            }
            
        //Menentukan Perbaruan STNK
            else if(cekStnk.isSelected()){
                adm = 60000;
            }
            break;
            
            case (1):
                swdkllj = 143000;
                
            if(cekBaru.isSelected()){
                bbnkb = harga * 10 / 100;
                adm = 100000;
            }
            
            else if(cekStnk.isSelected()){
                adm = 100000;
            }
            break;
        }
        
        //Menentukan Pajak Progresif
        switch(jumlah){
            case (0):
                pajak = 1.5 / 100;
        break;
            case (1) :
                pajak = 2.0 / 100;
        break;
            case (2) :
                pajak = 2.5 / 100;
        break;
            case (3) :
                pajak = 4.0 / 100;
        break;
        }
        
        hasil = harga * pajak + swdkllj + adm + bbnkb;
        kolomHasil.setText("Rp. "+hasil);
        
        infopajak info4 = new infopajak();
        info4.setInfo("Terima Kasih telah mengunakan Program Ini"
                + "\nPajak Anda Sebesar Rp. "+hasil);
        kolomInfo.setText(""+info4.getInfo());
    }//GEN-LAST:event_btnHitungActionPerformed

    private void kolomHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolomHargaKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE) || c=='.')){
            evt.consume();
        }
        if(c=='.' && kolomHarga.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_kolomHargaKeyTyped

    private void kolomHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomHargaActionPerformed

    private void cekStnkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekStnkActionPerformed
        if(cekStnk.isSelected()){
            cekBaru.setSelected(false);
        }
    }//GEN-LAST:event_cekStnkActionPerformed

    private void cekBaruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cekBaruKeyReleased

    }//GEN-LAST:event_cekBaruKeyReleased

    private void cekBaruKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cekBaruKeyPressed

    }//GEN-LAST:event_cekBaruKeyPressed

    private void cekStnkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cekStnkKeyPressed

    }//GEN-LAST:event_cekStnkKeyPressed

    private void btnInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfo1ActionPerformed
        if(btnInfo1.isSelected()){
            btnInfo2.setSelected(false);
            btnInfo3.setSelected(false);
        }
    }//GEN-LAST:event_btnInfo1ActionPerformed

    private void btnInfo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfo2ActionPerformed
        if(btnInfo2.isSelected()){
            btnInfo1.setSelected(false);
            btnInfo3.setSelected(false);
        }
    }//GEN-LAST:event_btnInfo2ActionPerformed

    private void btnInfo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfo3ActionPerformed
        if(btnInfo3.isSelected()){
            btnInfo1.setSelected(false);
            btnInfo2.setSelected(false);
        }
    }//GEN-LAST:event_btnInfo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Pajak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_Pajak().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnInfo;
    private javax.swing.JRadioButton btnInfo1;
    private javax.swing.JRadioButton btnInfo2;
    private javax.swing.JRadioButton btnInfo3;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox cekBaru;
    private javax.swing.JCheckBox cekStnk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kolomHarga;
    private javax.swing.JTextField kolomHasil;
    private javax.swing.JTextArea kolomInfo;
    private javax.swing.JComboBox<String> kolomJenis;
    private javax.swing.JComboBox<String> kolomJumlah;
    // End of variables declaration//GEN-END:variables
}
